name: Test Airflow DAGs

on:
    push:
        paths:
            - 'dags/**'
            - '.github/workflows/test_dags.yml'
    pull_request:
        paths:
            - 'dags/**'

jobs:
    test-dags:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.9'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install apache-airflow

        - name: Validate DAGs
          run: |
            for dag in dags/*.py; do
              python $dag
            done